version: '3'
services:
  db:
    container_name: megachasma-db
    image: postgres:14
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  graphql:
    container_name: megachasma-graphql
    build: .
    volumes:
    - .:/app
    ports:
    - '8000:8080'
    env_file:
    - .env
    depends_on:
    - db
    tty: true

  adminer:
    container_name: megachasma-adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata: null