FROM golang:1.17 as build

# コンテナ上にアプリケーション(main.goのビルド成果物)を配置するdirectoryを作成
WORKDIR /app

# ソースをコピー
COPY ./ ./
RUN go mod download

# docker コンテナの50001ポートをこのサービスのために使用
EXPOSE 50001

# apiサーバを起動
CMD ["go","run","server.go"]